# Generated by Django 3.2.2 on 2021-05-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
